/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

公式
Sn=2an+an-1-1
Sn奇数和等于偶数和
*/
package main

import "fmt"

func main() {
	max := 4000000
	now := 1
	before := 1
	for now < max {
		after := before + now
		if after > max {
			break
		}
		before = now
		now = after
		fmt.Println(now)
	}

	fmt.Println((before + 2*now - 1) / 2)
}
